#!/bin/bash
# pt-heartbeat_mysql        Init script for running percona tools
#
# chkconfig: 2345 90 02
#
# description: Init script for running percona tools


# source function library
lsb_functions="/lib/lsb/init-functions"

if test -f $lsb_functions ; then
  . $lsb_functions
else
  log_success_msg()
  {
    echo " SUCCESS! $@"
  }
  log_failure_msg()
  {
    echo " ERROR! $@"
  }
fi

# test for pt-heartbeat
[ $(type pt-heartbeat 2>&1| grep -c 'pt-heartbeat is') -gt 0 ] || {
	echo "I can't find pt-heartbeat on the path">&2
	exit 1
}

CONF=/etc/pt-heartbeat.cnf

# test for conf file
[ -r $CONF ] || {
   echo "I can't find or read $CONF">&2
   exit 1
}

# test for pid option
. $CONF
piderr=0
[ -z "$pid" ] && piderr=1 #if unset, error
[ -f $pid ] || {
   touch $pid || piderr=1 #if I can't touch, error
   rm -f $pid
}
[ $piderr -eq 1 ] && {
   echo "I can't find the pid option in $CONF, or it's value is invalid" >&2
   exit 1
}

op="$1"

# functions implementing options

start()
{
	echo -n "Starting pt-heartbeat ... "
#	pt-heartbeat --config $CONF --daemonize --update 
	pt-heartbeat --config $CONF --daemonize --update
	[ $? -eq 0 ] && log_success_msg || log_failure_msg 
}

stop()
{
	[ -f $pid ] && [ -d /proc/$(cat $pid) ] && {
		echo -n "Stopping pt-heartbeat ... "
		kill $(cat $pid)
		log_success_msg 
                rm $pid
	}|| {
		echo "pt-heartbeat is not running">&2
	}
}

status()
{
		[ -f $pid ] && [ -d /proc/$(cat $pid) ] && echo "pt-heartbeat is running" || echo "pt-heartbeat is not running">&2
}

case "$op" in 
	start)
      start
		;;		
	stop)	
      stop
		;;
   restart)
		stop
		start
		;;
	status) 
      status
		;;
	*)
		echo "Usage: $0 start|stop|restart|status">&2
		exit 1
esac

exit 0
